services:
  openldap:
    hostname: openldap
    image: osixia/openldap:latest
    container_name: open_ldap
    ports:
      - 389:389
      - 636:636
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    environment:
      - LDAP_DOMAIN=ldap.local.fr
      - LDAP_ADMIN_PASSWORD=passadmin
      - "LDAP_BASE_DN=dc=ldap,dc=local,dc=fr"
    networks:
      - open_ldap

  php:
    build: ./php
    ports: 
    - 90:80
    volumes:
      - ./php:/var/www/html
    networks:
      - open_ldap
volumes:
  ldap_data:
  ldap_config:
networks:
  open_ldap:
  