services:
  openldap:
    image: osixia/openldap:latest
    container_name: open_ldap
    ports:
      - 389:389
      - 636:636
    environment:
      - LDAP_ORGANISATION="local-ldap"
      - LDAP_DOMAIN="local.fr"
      - LDAP_ADMIN_PASSWORD="alf_admin"
      - LDAP_BASE_DN="dc=local,dc=fr"
    hostname: ldap.localdirectory.fr

  php:
    build: ./php
    ports: 
    - 80:80