services:
  openldap:
    image: osixia/openldap:latest
    container_name: open_ldap
    ports:
      - 389:389
      - 636:636
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ./certs:/container/service/slapd/assets/certs

    environment:
      - LDAP_ORGANISATION="ldap.fr"
      - LDAP_DOMAIN="ldap.localdirectory.fr"
      - LDAP_ADMIN_PASSWORD="alf_admin"
      - LDAP_BASE_DN="dc=ldap,dc=localdirectory,dc=fr"
    hostname: ldap.localdirectory.fr

  php:
    build: ./php
    ports: 
    - 90:80
volumes: 
  ldap_data:
  ldap_config:
