services:
  openldap:
    image: osixia/openldap:latest
    container_name: open_ldap
    ports:
      - 389:389
      - 636:636
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ./certs:/container/service/slapd/assets/certs

    environment:
      - LDAP_ORGANISATION=ldap.fr
      - LDAP_DOMAIN=ldap.local.fr
      - LDAP_ADMIN_USERNAME=admin 
      - LDAP_ADMIN_PASSWORD=admin
      - "LDAP_BASE_DN=dc=ldap,dc=local,dc=fr"
    hostname: ldap
    networks:
      - openldap
  php:
    build: ./php
    ports: 
      - "80:80"
    depends_on:
      - openldap

volumes: 
  ldap_data:
  ldap_config:

networks:
  openldap:
    driver: bridge
